### ISSUE TITLE
Make it work with Mongo 2.x

### ISSUE THREAD

**Issue by lepek** [taganaka/polipus#67]
I added a new mongo2_store, a mongo2_queue and a few other methods to make it work with the new driver MongoDB 2. 

I wonder if you are interested in a pull request with this, supporting mongo 1.x and mongo 2.x ruby driver, or your plans are to replace the current mongo implementation and update it in favor of the new driver.

**Comment by taganaka** [comment]
Hello @lepek 
My idea is to move away from client v1 and replace it with mongo client v2.

A PR is more than welcome! 

Thanks

**Comment by lepek** [comment]
Excellent then, I will submit a pull request then.
